-- Limpar registros anteriores para atualização completa
DELETE FROM treasury_ledger;

-- Inserir os 34 registros atualizados da Andressa de Lima Ferreira
INSERT INTO treasury_ledger (type, category, amount_cents, description, status, created_at) VALUES 
('outbound', 'membership', 500000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Nu Pagamentos) | Pix | Referencia: 08.jpg', 'completed', strftime('%s', '2023-08-08')),
('outbound', 'membership', 500000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Nu Pagamentos) | Pix | Referencia: 09.jpg', 'completed', strftime('%s', '2023-08-09')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Nu Pagamentos) | Pix | Referencia: 27.jpg', 'completed', strftime('%s', '2023-09-21')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Nu Pagamentos) | Pix | Referencia: 24.jpg', 'completed', strftime('%s', '2023-10-20')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Nu Pagamentos) | Pix | Referencia: 28.jpg', 'completed', strftime('%s', '2023-11-21')),
('outbound', 'membership', 70000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 29.jpg / 30.pdf', 'completed', strftime('%s', '2023-12-21')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 31.jpg / 32.jpg', 'completed', strftime('%s', '2023-12-22')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 15.jpg', 'completed', strftime('%s', '2024-02-16')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 12.jpg', 'completed', strftime('%s', '2024-03-11')),
('outbound', 'membership', 70000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 37.jpg / 01.pdf', 'completed', strftime('%s', '2024-04-30')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 38.jpg', 'completed', strftime('%s', '2024-04-30')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 36.jpg', 'completed', strftime('%s', '2024-05-29')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 33.jpg', 'completed', strftime('%s', '2024-06-24')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 35.pdf', 'completed', strftime('%s', '2024-07-28')),
('outbound', 'membership', 70000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 01.pdf', 'completed', strftime('%s', '2024-09-06')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 07.jpg', 'completed', strftime('%s', '2024-09-06')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 01.pdf', 'completed', strftime('%s', '2024-10-09')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 10.pdf', 'completed', strftime('%s', '2024-11-09')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 22.pdf', 'completed', strftime('%s', '2024-12-18')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 26.pdf', 'completed', strftime('%s', '2025-01-21')),
('outbound', 'membership', 70000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 25.pdf / 02.pdf', 'completed', strftime('%s', '2025-01-21')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 11.jpg', 'completed', strftime('%s', '2025-02-10')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 23.pdf', 'completed', strftime('%s', '2025-03-19')),
('outbound', 'membership', 40000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 21.pdf / 02.pdf', 'completed', strftime('%s', '2025-04-18')),
('outbound', 'membership', 40000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Sandro Alves de Amorim (Bradesco) | Pix | Referencia: 39.pdf / 02.pdf', 'completed', strftime('%s', '2025-04-30')),
('outbound', 'membership', 75000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 16.pdf', 'completed', strftime('%s', '2025-05-17')),
('outbound', 'membership', 35000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Sandro Alves de Amorim (Banco Inter) | Pix | Referencia: 17.jpg / 03.pdf', 'completed', strftime('%s', '2025-06-17')),
('outbound', 'membership', 80000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 18.pdf', 'completed', strftime('%s', '2025-06-17')),
('outbound', 'membership', 66700, 'Pagador: Andressa de Lima Ferreira (Nu Pagamentos) | Favorecido: Sandro Alves de Amorim (Banco Inter) | Pix | Referencia: 34.jpg / 03.pdf', 'completed', strftime('%s', '2025-07-26')),
('outbound', 'membership', 66700, 'Pagador: Andressa de Lima Ferreira (Nu Pagamentos) | Favorecido: Paulo Roberto Batista Ferreira (Itaú Unibanco) | Pix | Referencia: 04.jpg', 'completed', strftime('%s', '2025-08-02')),
('outbound', 'membership', 66700, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Sandro Alves de Amorim (Banco Inter) | Pix | Referencia: 14.jpg / 03.pdf', 'completed', strftime('%s', '2025-08-15')),
('outbound', 'membership', 100000, 'Pagador: Andressa de Lima Ferreira (Itaú Unibanco) | Favorecido: Paulo Roberto Batista Ferreira (Santander) | Pix | Referencia: 13.jpg', 'completed', strftime('%s', '2025-10-13')),
('outbound', 'membership', 105000, 'Pagador: Andressa de Lima Ferreira (Mercado Pago) | Favorecido: ASPPIBRA (Cora SCFI) | Boleto | Referencia: 20.pdf / 19.pdf', 'completed', strftime('%s', '2025-11-17')),
('outbound', 'membership', 55000, 'Pagador: Andressa de Lima Ferreira (Nu Pagamentos) | Favorecido: ASPPIBRA (Cora SCFI) | Pix | Referencia: 05.jpg / 06.pdf', 'completed', strftime('%s', '2025-12-05'));
